before:
  hooks:
    - go mod tidy

builds:
  - id: nbot
    main: ./cmd/nbot/main.go
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Tag}}
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - 386

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}-{{ .Version }}"
    format: binary
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

changelog:
  skip: true
