version: "3.8"

services:
  nbot:
    image: ghcr.io/milgradesec/nbot:latest
    read_only: true
    networks:
      - db_network
    environment:
      - DISCORD_BOT_TOKEN_FILE=/run/secrets/nbot_discord_token
      - POSTGRES_HOST=pgsql-prod.paesa.es:5432
      - POSTGRES_DB=nbot
      - POSTGRES_USER=nbot
      - POSTGRES_DB_PASSWORD_FILE=/run/secrets/nbot_db_password
      - SSL_ROOT_CERT=/run/secrets/paesa_ca_crt
      - S3_ACCESS_KEY_FILE=/run/secrets/nbot_s3_access_key
      - S3_SECRET_KEY_FILE=/run/secrets/nbot_s3_secret_key
      - RIOT_APIKEY_FILE=/run/secrets/nbot_riot_apikey
    secrets:
      - nbot_discord_token
      - nbot_db_password
      - nbot_s3_access_key
      - nbot_s3_secret_key
      - nbot_riot_apikey
      - paesa_ca_crt
    logging:
      options:
        max-size: 1MB
    cap_drop:
      - ALL
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

secrets:
  nbot_discord_token:
    external: true
  nbot_db_password:
    external: true
  nbot_s3_access_key:
    external: true
  nbot_s3_secret_key:
    external: true
  nbot_riot_apikey:
    external: true
  paesa_ca_crt:
    external: true

networks:
  db_network:
    external: true
