name: Lint

on: [push, pull_request]

jobs:
  golangci:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ^1.20

      - name: Run
        uses: golangci/golangci-lint-action@v8
